#!/bin/sh

set -eu

HOST="$1"

CLASSES=$(ldapsearch -H ldaps://db.oftc.net \
	-b ou=hosts,dc=oftc,dc=net \
	-x "(&(objectclass=puppetClient)(hostname=$HOST))" \
	puppetclass | sed -ne 's/puppetClass:/ -/p')

if [ "$CLASSES" ]; then
	echo "classes:"
	echo "$CLASSES"
else
	exit 1
fi

