#!/bin/bash

set -eu

HOST="$1"
[ "$HOST" = "strange" ] && HOST="zombie-scan"
DATE1=$(date '+%Y-%m-%d')
DATE2=$(date '+%Y-%m-%d' -d 'now -4 hours')

for f in /var/log/hosts/$HOST/syslog-{$DATE1,$DATE2}.log{,.bz2}; do
  if [ -f "$f" ]; then
    echo "OK: $f"
    exit 0
  fi
done

echo "WARNING: /var/log/hosts/$HOST/syslog-$DATE1.log is missing"
exit 1
